name: Downgrade
on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
jobs:
  test:
    strategy:
      matrix:
        group:
          - Core
        julia-version: ['lts']
    uses: "SciML/.github/.github/workflows/downgrade.yml@v1"
    with:
      julia-version: "${{ matrix.julia-version }}"
      group: "${{ matrix.group }}"
      projects: "."
    secrets: "inherit"
